#!/bin/sh
set -e
[ -f /etc/inside-container ] || exec script/app-env "$0" "$@"
script/clean
echo "compiling coffeescript"
node_modules/.bin/coffee -c -o dist lib/main.coffee
find ./public -maxdepth 1 -type f \( -iname \*.js -o -iname \*.css \) -print0 | xargs -n 1 -0 -I{} cp -v {} dist/
